/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistes;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import models.Professor;
import vistes.panels.CanviaPanel;


/**
 *
 * @author Montse
 */
public class PM02Menu extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form PM02Menu
     */
    public PM02Menu() {
        initComponents();
        this.setSize(750, 625);
        this.setLocationRelativeTo(this);
        this.rSBtInici.setSelected(true);
        
        jPanel1.setSize(750, 625);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanelBarraSup = new javax.swing.JPanel();
        lbUsuari = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        btMenu = new javax.swing.JButton();
        jPanelEsqLlisc = new javax.swing.JPanel();
        rSBtInici = new recursos.rsbuttom.RSButtonMetro();
        rSBtUsuaris = new recursos.rsbuttom.RSButtonMetro();
        rSBtRanquing = new recursos.rsbuttom.RSButtonMetro();
        rSBtJoc = new recursos.rsbuttom.RSButtonMetro();
        jPanelPrinc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPInicial = new javax.swing.JPanel();
        lbBenvinguts = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(162, 215, 41));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 600));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanelBarraSup.setBackground(new java.awt.Color(251, 139, 36));
        jPanelBarraSup.setPreferredSize(new java.awt.Dimension(396, 86));

        lbUsuari.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        lbUsuari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon_rounded_user_login.png"))); // NOI18N
        lbUsuari.setText("Eduard");
        lbUsuari.setIconTextGap(15);
        lbUsuari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUsuariMouseClicked(evt);
            }
        });

        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon_exit2_64.png"))); // NOI18N
        lbLogout.setToolTipText("Logout");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });

        btMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon_menu_64.png"))); // NOI18N
        btMenu.setBorderPainted(false);
        btMenu.setContentAreaFilled(false);
        btMenu.setFocusPainted(false);
        btMenu.setMaximumSize(new java.awt.Dimension(64, 64));
        btMenu.setMinimumSize(new java.awt.Dimension(64, 64));
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBarraSupLayout = new javax.swing.GroupLayout(jPanelBarraSup);
        jPanelBarraSup.setLayout(jPanelBarraSupLayout);
        jPanelBarraSupLayout.setHorizontalGroup(
            jPanelBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraSupLayout.createSequentialGroup()
                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(lbUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbLogout)
                .addContainerGap())
        );
        jPanelBarraSupLayout.setVerticalGroup(
            jPanelBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraSupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogout)
                    .addComponent(lbUsuari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarraSupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(jPanelBarraSup, gridBagConstraints);

        jPanelEsqLlisc.setBackground(new java.awt.Color(239, 247, 207));

        rSBtInici.setBorder(null);
        rSBtInici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/001-home-page.png"))); // NOI18N
        rSBtInici.setText("Inici");
        rSBtInici.setColorHover(new java.awt.Color(189, 197, 157));
        rSBtInici.setColorNormal(new java.awt.Color(209, 217, 177));
        rSBtInici.setColorPressed(new java.awt.Color(189, 197, 157));
        rSBtInici.setColorTextHover(new java.awt.Color(239, 247, 207));
        rSBtInici.setColorTextNormal(new java.awt.Color(23, 33, 33));
        rSBtInici.setColorTextPressed(new java.awt.Color(239, 247, 207));
        rSBtInici.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSBtInici.setIconTextGap(15);
        rSBtInici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rSBtIniciMousePressed(evt);
            }
        });
        rSBtInici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSBtIniciActionPerformed(evt);
            }
        });

        rSBtUsuaris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/002-multiple-users-silhouette.png"))); // NOI18N
        rSBtUsuaris.setText("Usuaris");
        rSBtUsuaris.setColorHover(new java.awt.Color(189, 197, 157));
        rSBtUsuaris.setColorNormal(new java.awt.Color(209, 217, 177));
        rSBtUsuaris.setColorPressed(new java.awt.Color(189, 197, 157));
        rSBtUsuaris.setColorTextHover(new java.awt.Color(239, 247, 207));
        rSBtUsuaris.setColorTextNormal(new java.awt.Color(23, 33, 33));
        rSBtUsuaris.setColorTextPressed(new java.awt.Color(239, 247, 207));
        rSBtUsuaris.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSBtUsuaris.setIconTextGap(15);
        rSBtUsuaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rSBtUsuarisMousePressed(evt);
            }
        });
        rSBtUsuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSBtUsuarisActionPerformed(evt);
            }
        });

        rSBtRanquing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/004-rank.png"))); // NOI18N
        rSBtRanquing.setText("Rànquing");
        rSBtRanquing.setColorHover(new java.awt.Color(189, 197, 157));
        rSBtRanquing.setColorNormal(new java.awt.Color(209, 217, 177));
        rSBtRanquing.setColorPressed(new java.awt.Color(189, 197, 157));
        rSBtRanquing.setColorTextHover(new java.awt.Color(239, 247, 207));
        rSBtRanquing.setColorTextNormal(new java.awt.Color(23, 33, 33));
        rSBtRanquing.setColorTextPressed(new java.awt.Color(239, 247, 207));
        rSBtRanquing.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSBtRanquing.setIconTextGap(15);
        rSBtRanquing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rSBtRanquingMousePressed(evt);
            }
        });
        rSBtRanquing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSBtRanquingActionPerformed(evt);
            }
        });

        rSBtJoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/003-dice.png"))); // NOI18N
        rSBtJoc.setText("Joc");
        rSBtJoc.setColorHover(new java.awt.Color(189, 197, 157));
        rSBtJoc.setColorNormal(new java.awt.Color(209, 217, 177));
        rSBtJoc.setColorPressed(new java.awt.Color(189, 197, 157));
        rSBtJoc.setColorTextHover(new java.awt.Color(239, 247, 207));
        rSBtJoc.setColorTextNormal(new java.awt.Color(23, 33, 33));
        rSBtJoc.setColorTextPressed(new java.awt.Color(239, 247, 207));
        rSBtJoc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSBtJoc.setIconTextGap(15);
        rSBtJoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rSBtJocMousePressed(evt);
            }
        });
        rSBtJoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSBtJocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEsqLliscLayout = new javax.swing.GroupLayout(jPanelEsqLlisc);
        jPanelEsqLlisc.setLayout(jPanelEsqLliscLayout);
        jPanelEsqLliscLayout.setHorizontalGroup(
            jPanelEsqLliscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSBtInici, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            .addComponent(rSBtUsuaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSBtRanquing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSBtJoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEsqLliscLayout.setVerticalGroup(
            jPanelEsqLliscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEsqLliscLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(rSBtInici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSBtUsuaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSBtRanquing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSBtJoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jPanelEsqLlisc, gridBagConstraints);

        jPanelPrinc.setBackground(new java.awt.Color(162, 215, 41));

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 500));

        jPInicial.setBackground(new java.awt.Color(162, 215, 41));
        jPInicial.setMaximumSize(new java.awt.Dimension(3600, 2400));
        jPInicial.setMinimumSize(new java.awt.Dimension(40, 30));
        jPInicial.setLayout(new javax.swing.BoxLayout(jPInicial, javax.swing.BoxLayout.LINE_AXIS));

        lbBenvinguts.setFont(new java.awt.Font("Raleway", 1, 30)); // NOI18N
        lbBenvinguts.setText("Benvinguts");
        jPInicial.add(lbBenvinguts);

        lbLogo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(23, 33, 33));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon_logo_saberapp_64.png"))); // NOI18N
        lbLogo.setText("SaberApp");
        jPInicial.add(lbLogo);

        jScrollPane1.setViewportView(jPInicial);

        javax.swing.GroupLayout jPanelPrincLayout = new javax.swing.GroupLayout(jPanelPrinc);
        jPanelPrinc.setLayout(jPanelPrincLayout);
        jPanelPrincLayout.setHorizontalGroup(
            jPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
        );
        jPanelPrincLayout.setVerticalGroup(
            jPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelPrinc, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        int position = this.jPanelEsqLlisc.getX();
        if (position > -1) {
            Animacion.Animacion.mover_izquierda(0, -150, 2, 2, jPanelEsqLlisc);
        } else {
            Animacion.Animacion.mover_derecha(-150, 0, 2, 2, jPanelEsqLlisc);
        }
    }//GEN-LAST:event_btMenuActionPerformed
    //TODO segons l.201-202 de PM01Login
    //Professor p =new Professor();
    String nick;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lbUsuari.setText(nick);
    }//GEN-LAST:event_formWindowActivated

    private void rSBtIniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSBtIniciActionPerformed
        new CanviaPanel(jPInicial, new vistes.panels.PM08Inici());
        if(this.rSBtInici.isSelected()){
            this.rSBtInici.setColorNormal(new Color(189,197,157));
            this.rSBtInici.setColorTextNormal(new Color(239,247,207));
            this.rSBtInici.setColorHover(new Color(189,197,157));
            this.rSBtInici.setColorPressed(new Color(189,197,157));
            
            this.rSBtUsuaris.setColorNormal(new Color(209,217,177));
            this.rSBtUsuaris.setColorTextNormal(new Color(23,33,33));
            this.rSBtUsuaris.setColorHover(new Color(189,197,157));
            this.rSBtUsuaris.setColorPressed(new Color(189,197,157));
            
            this.rSBtRanquing.setColorNormal(new Color(209,217,177));
            this.rSBtRanquing.setColorTextNormal(new Color(23,33,33));
            this.rSBtRanquing.setColorHover(new Color(189,197,157));
            this.rSBtRanquing.setColorPressed(new Color(189,197,157));
            
            this.rSBtJoc.setColorNormal(new Color(209,217,177));
            this.rSBtJoc.setColorTextNormal(new Color(23,33,33));
            this.rSBtJoc.setColorHover(new Color(189,197,157));
            this.rSBtJoc.setColorPressed(new Color(189,197,157));
            
        }else{
            this.rSBtInici.setColorNormal(new Color(209,217,177));
            this.rSBtInici.setColorTextNormal(new Color(23,33,33));
            this.rSBtInici.setColorHover(new Color(189,197,157));
            this.rSBtInici.setColorPressed(new Color(189,197,157));
        }
    }//GEN-LAST:event_rSBtIniciActionPerformed

    private void rSBtIniciMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSBtIniciMousePressed
        this.rSBtInici.setSelected(true);
        this.rSBtUsuaris.setSelected(false);
        this.rSBtRanquing.setSelected(false);
        this.rSBtJoc.setSelected(false);
    }//GEN-LAST:event_rSBtIniciMousePressed

    private void rSBtUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSBtUsuarisActionPerformed
        new CanviaPanel(jPInicial, new vistes.panels.PM06Jugadors());
        if(this.rSBtUsuaris.isSelected()){
            this.rSBtInici.setColorNormal(new Color(209,217,177));
            this.rSBtInici.setColorTextNormal(new Color(23,33,33));
            this.rSBtInici.setColorHover(new Color(189,197,157));
            this.rSBtInici.setColorPressed(new Color(189,197,157));
            
            this.rSBtUsuaris.setColorNormal(new Color(189,197,157));
            this.rSBtUsuaris.setColorTextNormal(new Color(239,247,207));
            this.rSBtUsuaris.setColorHover(new Color(189,197,157));
            this.rSBtUsuaris.setColorPressed(new Color(189,197,157));
            
            this.rSBtRanquing.setColorNormal(new Color(209,217,177));
            this.rSBtRanquing.setColorTextNormal(new Color(23,33,33));
            this.rSBtRanquing.setColorHover(new Color(189,197,157));
            this.rSBtRanquing.setColorPressed(new Color(189,197,157));
            
            this.rSBtJoc.setColorNormal(new Color(209,217,177));
            this.rSBtJoc.setColorTextNormal(new Color(23,33,33));
            this.rSBtJoc.setColorHover(new Color(189,197,157));
            this.rSBtJoc.setColorPressed(new Color(189,197,157));
            
        }else{
            this.rSBtUsuaris.setColorNormal(new Color(209,217,177));
            this.rSBtUsuaris.setColorTextNormal(new Color(23,33,33));
            this.rSBtUsuaris.setColorHover(new Color(189,197,157));
            this.rSBtUsuaris.setColorPressed(new Color(189,197,157));
        }
    }//GEN-LAST:event_rSBtUsuarisActionPerformed

    private void rSBtUsuarisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSBtUsuarisMousePressed
        this.rSBtInici.setSelected(false);
        this.rSBtUsuaris.setSelected(true);
        this.rSBtRanquing.setSelected(false);
        this.rSBtJoc.setSelected(false);
    }//GEN-LAST:event_rSBtUsuarisMousePressed

    private void rSBtRanquingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSBtRanquingActionPerformed
        new CanviaPanel(jPInicial, new vistes.panels.PM07Ranquing());
        if(this.rSBtRanquing.isSelected()){
            this.rSBtInici.setColorNormal(new Color(209,217,177));
            this.rSBtInici.setColorTextNormal(new Color(23,33,33));
            this.rSBtInici.setColorHover(new Color(189,197,157));
            this.rSBtInici.setColorPressed(new Color(189,197,157));
            
            this.rSBtUsuaris.setColorNormal(new Color(209,217,177));
            this.rSBtUsuaris.setColorTextNormal(new Color(23,33,33));
            this.rSBtUsuaris.setColorHover(new Color(189,197,157));
            this.rSBtUsuaris.setColorPressed(new Color(189,197,157));
            
            this.rSBtRanquing.setColorNormal(new Color(189,197,157));
            this.rSBtRanquing.setColorTextNormal(new Color(239,247,207));
            this.rSBtRanquing.setColorHover(new Color(189,197,157));
            this.rSBtRanquing.setColorPressed(new Color(189,197,157));
            
            this.rSBtJoc.setColorNormal(new Color(209,217,177));
            this.rSBtJoc.setColorTextNormal(new Color(23,33,33));
            this.rSBtJoc.setColorHover(new Color(189,197,157));
            this.rSBtJoc.setColorPressed(new Color(189,197,157));
            
        }else{
            this.rSBtRanquing.setColorNormal(new Color(209,217,177));
            this.rSBtRanquing.setColorTextNormal(new Color(23,33,33));
            this.rSBtRanquing.setColorHover(new Color(189,197,157));
            this.rSBtRanquing.setColorPressed(new Color(189,197,157));
        }
    }//GEN-LAST:event_rSBtRanquingActionPerformed

    private void rSBtRanquingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSBtRanquingMousePressed
        this.rSBtInici.setSelected(false);
        this.rSBtUsuaris.setSelected(false);
        this.rSBtRanquing.setSelected(true);
        this.rSBtJoc.setSelected(false);
    }//GEN-LAST:event_rSBtRanquingMousePressed

    private void rSBtJocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSBtJocActionPerformed
        new CanviaPanel(jPInicial, new vistes.panels.PM05Joc());
        
        if(this.rSBtJoc.isSelected()){
            this.rSBtInici.setColorNormal(new Color(209,217,177));
            this.rSBtInici.setColorTextNormal(new Color(23,33,33));
            this.rSBtInici.setColorHover(new Color(189,197,157));
            this.rSBtInici.setColorPressed(new Color(189,197,157));
            
            this.rSBtUsuaris.setColorNormal(new Color(209,217,177));
            this.rSBtUsuaris.setColorTextNormal(new Color(23,33,33));
            this.rSBtUsuaris.setColorHover(new Color(189,197,157));
            this.rSBtUsuaris.setColorPressed(new Color(189,197,157));
            
            this.rSBtRanquing.setColorNormal(new Color(209,217,177));
            this.rSBtRanquing.setColorTextNormal(new Color(23,33,33));
            this.rSBtRanquing.setColorHover(new Color(189,197,157));
            this.rSBtRanquing.setColorPressed(new Color(189,197,157));
            
            this.rSBtJoc.setColorNormal(new Color(189,197,157));
            this.rSBtJoc.setColorTextNormal(new Color(239,247,207));
            this.rSBtJoc.setColorHover(new Color(189,197,157));
            this.rSBtJoc.setColorPressed(new Color(189,197,157));
            
        }else{
            this.rSBtJoc.setColorNormal(new Color(209,217,177));
            this.rSBtJoc.setColorTextNormal(new Color(23,33,33));
            this.rSBtJoc.setColorHover(new Color(189,197,157));
            this.rSBtJoc.setColorPressed(new Color(189,197,157));
        }
    }//GEN-LAST:event_rSBtJocActionPerformed

    private void rSBtJocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSBtJocMousePressed
        this.rSBtInici.setSelected(false);
        this.rSBtUsuaris.setSelected(false);
        this.rSBtRanquing.setSelected(false);
        this.rSBtJoc.setSelected(true);
    }//GEN-LAST:event_rSBtJocMousePressed

    private void lbUsuariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUsuariMouseClicked
        new CanviaPanel(jPInicial, new vistes.panels.PM04Modifica(nick));
    }//GEN-LAST:event_lbUsuariMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM02Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMenu;
    private javax.swing.JPanel jPInicial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBarraSup;
    private javax.swing.JPanel jPanelEsqLlisc;
    private javax.swing.JPanel jPanelPrinc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBenvinguts;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbUsuari;
    private recursos.rsbuttom.RSButtonMetro rSBtInici;
    private recursos.rsbuttom.RSButtonMetro rSBtJoc;
    private recursos.rsbuttom.RSButtonMetro rSBtRanquing;
    private recursos.rsbuttom.RSButtonMetro rSBtUsuaris;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        Object evt = e.getSource();
        
        if(evt.equals(lbUsuari)){
            //vistes.panels.CanviaPanel(jPanelPrinc,vistes.PM04Settings.jPModificar);
        }
                }
}
