/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistes;

import java.awt.Color;

/**
 *
 * @author montse
 */
public class PM05ACrearJoc extends javax.swing.JFrame {

    private String subject;
    private String materia;
    private int num_jornada;
    private String data_inici;
    private String data_final;
    private int num_pregunta;
    private String enunciat;
    private String resposta_A, resposta_B, resposta_C, resposta_D;
    private String correcció;
    private String url_image;
    

    /**
     * Creates new form PM05ACrearJoc
     */
    public PM05ACrearJoc() {
        initComponents();
        this.setSize(750, 600);
        this.setLocationRelativeTo(this);
        
        jPanel1.setSize(750, 600);
        
        cbMateria.addItem("Mates");
        cbMateria.addItem("Art");
        cbMateria.addItem("English");
        cbMateria.addItem("Història");
        cbMateria.addItem("Filosofia");
        
        this.jButton1.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbMateria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btDesaTot = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPIniciPubli = new javax.swing.JPanel();
        lbDia = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        lbAny = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbAny = new javax.swing.JComboBox<>();
        jPFiPubli = new javax.swing.JPanel();
        lbDia1 = new javax.swing.JLabel();
        lbMes1 = new javax.swing.JLabel();
        lbAny1 = new javax.swing.JLabel();
        cbDia1 = new javax.swing.JComboBox<>();
        cbMes1 = new javax.swing.JComboBox<>();
        cbAny1 = new javax.swing.JComboBox<>();
        jPPregunta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbNumPreg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEnunciat = new javax.swing.JTextArea();
        rdBtRespA = new javax.swing.JRadioButton();
        txtRespostaA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdBtRespB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtRespostaB = new javax.swing.JTextField();
        rdBtRespC = new javax.swing.JRadioButton();
        txtRespostaC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdBtRespD = new javax.swing.JRadioButton();
        txtRespostaD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCorreccio = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtImatgeUrl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btGuardaPregunta = new javax.swing.JButton();
        btConfirmaMateria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 215, 41));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 600));

        cbMateria.setBackground(new java.awt.Color(239, 247, 207));
        cbMateria.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cbMateria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMateriaItemStateChanged(evt);
            }
        });

        jLabel1.setText("Joc nº 1 - SaberArt");

        btDesaTot.setText("Desa i torna");
        btDesaTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesaTotActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9MousePressed(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("10");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPIniciPubli.setBorder(javax.swing.BorderFactory.createTitledBorder("Inici publicació"));

        lbDia.setText("Dia");

        lbMes.setText("Mes");

        lbAny.setText("Any");

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gener", "Febrer", "Març", "Abril", "Maig", "Juny", "Juliol", "Agost", "Setembre", "Octubre", "Novembre", "Desembre" }));

        cbAny.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023" }));

        javax.swing.GroupLayout jPIniciPubliLayout = new javax.swing.GroupLayout(jPIniciPubli);
        jPIniciPubli.setLayout(jPIniciPubliLayout);
        jPIniciPubliLayout.setHorizontalGroup(
            jPIniciPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPIniciPubliLayout.createSequentialGroup()
                .addGroup(jPIniciPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPIniciPubliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDia))
                    .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPIniciPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPIniciPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAny)
                    .addComponent(cbAny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPIniciPubliLayout.setVerticalGroup(
            jPIniciPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPIniciPubliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPIniciPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDia)
                    .addComponent(lbMes)
                    .addComponent(lbAny))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPIniciPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPFiPubli.setBorder(javax.swing.BorderFactory.createTitledBorder("Fi publicació"));

        lbDia1.setText("Dia");

        lbMes1.setText("Mes");

        lbAny1.setText("Any");

        cbDia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gener", "Febrer", "Març", "Abril", "Maig", "Juny", "Juliol", "Agost", "Setembre", "Octubre", "Novembre", "Desembre" }));

        cbAny1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023" }));

        javax.swing.GroupLayout jPFiPubliLayout = new javax.swing.GroupLayout(jPFiPubli);
        jPFiPubli.setLayout(jPFiPubliLayout);
        jPFiPubliLayout.setHorizontalGroup(
            jPFiPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFiPubliLayout.createSequentialGroup()
                .addGroup(jPFiPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFiPubliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDia1))
                    .addComponent(cbDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFiPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMes1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFiPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAny1)
                    .addComponent(cbAny1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFiPubliLayout.setVerticalGroup(
            jPFiPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFiPubliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPFiPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDia1)
                    .addComponent(lbMes1)
                    .addComponent(lbAny1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFiPubliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAny1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPPregunta.setBorder(javax.swing.BorderFactory.createTitledBorder("Pregunta"));

        jLabel2.setText("Enunciat");

        lbNumPreg.setText("preg. 1");

        txtEnunciat.setColumns(20);
        txtEnunciat.setRows(5);
        jScrollPane1.setViewportView(txtEnunciat);

        rdBtRespA.setText("Correcta");

        txtRespostaA.setText("Resposta1");

        jLabel4.setText("resp. a)");

        rdBtRespB.setText("Correcta");

        jLabel5.setText("resp. b)");

        txtRespostaB.setText("Resposta2");

        rdBtRespC.setText("Correcta");

        txtRespostaC.setText("Resposta3");

        jLabel6.setText("resp. c)");

        rdBtRespD.setText("Correcta");

        txtRespostaD.setText("Resposta4");

        jLabel7.setText("resp. d)");

        txtCorreccio.setColumns(20);
        txtCorreccio.setRows(5);
        jScrollPane2.setViewportView(txtCorreccio);

        jLabel8.setText("Feedback");

        txtImatgeUrl.setText("url");

        jLabel9.setText("Imatge");

        btGuardaPregunta.setText("Guarda");
        btGuardaPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardaPreguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPreguntaLayout = new javax.swing.GroupLayout(jPPregunta);
        jPPregunta.setLayout(jPPreguntaLayout);
        jPPreguntaLayout.setHorizontalGroup(
            jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(lbNumPreg)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPreguntaLayout.createSequentialGroup()
                        .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPPreguntaLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtRespostaA))
                            .addGroup(jPPreguntaLayout.createSequentialGroup()
                                .addComponent(txtRespostaB, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtRespostaC)
                            .addComponent(txtRespostaD))
                        .addGap(18, 18, 18)
                        .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdBtRespD)
                                .addComponent(rdBtRespC))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdBtRespB)
                                .addComponent(rdBtRespA))))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(txtImatgeUrl))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPreguntaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGuardaPregunta)
                .addGap(250, 250, 250))
        );
        jPPreguntaLayout.setVerticalGroup(
            jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPreguntaLayout.createSequentialGroup()
                .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPreguntaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNumPreg))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRespostaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdBtRespA)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRespostaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(rdBtRespB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPreguntaLayout.createSequentialGroup()
                        .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRespostaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRespostaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPPreguntaLayout.createSequentialGroup()
                        .addComponent(rdBtRespC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdBtRespD)))
                .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPreguntaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPreguntaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImatgeUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(btGuardaPregunta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btConfirmaMateria.setText("Confirma");
        btConfirmaMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btConfirmaMateriaMousePressed(evt);
            }
        });
        btConfirmaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmaMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btDesaTot, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(109, 109, 109))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPIniciPubli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btConfirmaMateria)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPFiPubli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btConfirmaMateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPIniciPubli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPFiPubli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addGap(28, 28, 28)
                        .addComponent(btDesaTot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMateriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMateriaItemStateChanged
        subject = (String) cbMateria.getSelectedItem();
    }//GEN-LAST:event_cbMateriaItemStateChanged

    private void btGuardaPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardaPreguntaActionPerformed
        // TODO llegeix inputs i botó num pregunta seleccionat. Guarda com objecte pregunta
        
    }//GEN-LAST:event_btGuardaPreguntaActionPerformed

    private void btConfirmaMateriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmaMateriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmaMateriaMousePressed

    private void btConfirmaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmaMateriaActionPerformed
        // TODO add your handling code here:
        materia = (String) cbMateria.getSelectedItem();
    }//GEN-LAST:event_btConfirmaMateriaActionPerformed

    private void btDesaTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesaTotActionPerformed
        // TODO recopila les dades de la partida, empaqueta i desa a la base de dades
        //aconsegueix data_inici i data_final
        data_inici=((String) cbDia.getSelectedItem()+"/"+cbMes.getSelectedItem()+"/"+cbAny.getSelectedItem());
        data_final=((String) cbDia1.getSelectedItem()+"/"+cbMes1.getSelectedItem()+"/"+cbAny1.getSelectedItem());
        
    }//GEN-LAST:event_btDesaTotActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        jButton1.setSelected(true);
        jButton2.setSelected(false);
        jButton3.setSelected(false);
        jButton4.setSelected(false);
        jButton5.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(false);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 1");
        
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton1.isSelected()){
            jButton1.setBackground(new Color(102,102,102));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton1.setBackground(new Color(238,238,238));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(true);
        jButton3.setSelected(false);
        jButton4.setSelected(false);
        jButton5.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(false);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 2");
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton2.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(102,102,102));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton2.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(false);
        jButton3.setSelected(true);
        jButton4.setSelected(false);
        jButton5.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(false);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 3");
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton3.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(102,102,102));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton3.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(false);
        jButton3.setSelected(false);
        jButton4.setSelected(true);
        jButton5.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(false);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 4");
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton4.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(102,102,102));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton4.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(false);
        jButton3.setSelected(false);
        jButton4.setSelected(false);
        jButton5.setSelected(true);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(false);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 5");
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton5.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(102,102,102));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton5.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(false);
        jButton3.setSelected(false);
        jButton4.setSelected(false);
        jButton5.setSelected(false);
        jButton6.setSelected(true);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(false);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 6");
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton6.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(102,102,102));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton6.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(false);
        jButton3.setSelected(false);
        jButton4.setSelected(false);
        jButton5.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(true);
        jButton8.setSelected(false);
        jButton9.setSelected(false);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 7");
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton7.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(102,102,102));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton7.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(false);
        jButton3.setSelected(false);
        jButton4.setSelected(false);
        jButton5.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(true);
        jButton9.setSelected(false);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 8");
    }//GEN-LAST:event_jButton8MousePressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton8.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(102,102,102));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton8.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(false);
        jButton3.setSelected(false);
        jButton4.setSelected(false);
        jButton5.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(true);
        jButton10.setSelected(false);
        
        lbNumPreg.setText("preg. 9");
    }//GEN-LAST:event_jButton9MousePressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton9.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(102,102,102));
            jButton10.setBackground(new Color(238,238,238));
        }else{
            jButton9.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        jButton1.setSelected(false);
        jButton2.setSelected(false);
        jButton3.setSelected(false);
        jButton4.setSelected(false);
        jButton5.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(false);
        jButton10.setSelected(true);
        
        lbNumPreg.setText("preg. 10");
    }//GEN-LAST:event_jButton10MousePressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //TODO afegir assegurar que s'han desat canvis abans de canviar pregunta
        netejaPregunta();
        if (this.jButton10.isSelected()){
            jButton1.setBackground(new Color(238,238,238));
            jButton2.setBackground(new Color(238,238,238));
            jButton3.setBackground(new Color(238,238,238));
            jButton4.setBackground(new Color(238,238,238));
            jButton5.setBackground(new Color(238,238,238));
            jButton6.setBackground(new Color(238,238,238));
            jButton7.setBackground(new Color(238,238,238));
            jButton8.setBackground(new Color(238,238,238));
            jButton9.setBackground(new Color(238,238,238));
            jButton10.setBackground(new Color(102,102,102));
        }else{
            jButton10.setBackground(new Color(238,238,238));
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM05ACrearJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM05ACrearJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM05ACrearJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM05ACrearJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM05ACrearJoc().setVisible(true);
            }
        });
    }
    
    private void netejaPregunta(){
        txtEnunciat.setText("");
        txtRespostaA.setText("");
        txtRespostaB.setText("");
        txtRespostaC.setText("");
        txtRespostaD.setText("");
        txtCorreccio.setText("");
        txtImatgeUrl.setText("");
        rdBtRespA.setSelected(false);
        rdBtRespB.setSelected(false);
        rdBtRespC.setSelected(false);
        rdBtRespD.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmaMateria;
    private javax.swing.JButton btDesaTot;
    private javax.swing.JButton btGuardaPregunta;
    private javax.swing.JComboBox<String> cbAny;
    private javax.swing.JComboBox<String> cbAny1;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbDia1;
    private javax.swing.JComboBox<String> cbMateria;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbMes1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPFiPubli;
    private javax.swing.JPanel jPIniciPubli;
    private javax.swing.JPanel jPPregunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAny;
    private javax.swing.JLabel lbAny1;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbDia1;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbMes1;
    private javax.swing.JLabel lbNumPreg;
    private javax.swing.JRadioButton rdBtRespA;
    private javax.swing.JRadioButton rdBtRespB;
    private javax.swing.JRadioButton rdBtRespC;
    private javax.swing.JRadioButton rdBtRespD;
    private javax.swing.JTextArea txtCorreccio;
    private javax.swing.JTextArea txtEnunciat;
    private javax.swing.JTextField txtImatgeUrl;
    private javax.swing.JTextField txtRespostaA;
    private javax.swing.JTextField txtRespostaB;
    private javax.swing.JTextField txtRespostaC;
    private javax.swing.JTextField txtRespostaD;
    // End of variables declaration//GEN-END:variables
}
