/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistes;

import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import models.Partida;

/**
 *
 * @author montse
 */
public class PM05BGestionaJoc extends javax.swing.JFrame {
    
    private ModelTaulaDadesJoc modelTaulaPartides;
    
    //SaberAppClient sac = new SaberAppClientImpl();
    List<String> nomsJocs = new ArrayList<>();

    /**
     * Creates new form PM05BGestionaJoc
     */
    public PM05BGestionaJoc() throws ParseException {
        initComponents();
        this.setSize(750, 600);
        this.setLocationRelativeTo(this);
        /*
        //Recuperem tots els jocs a la base de dades
        jocs = sac.getAllJocs();

        //Afegim els jocs al select
        for (Joc j : jocs) {
            cbJoc.addItem(j);
        }
        */
        jPanel1.setSize(750, 600);
        
        setModelTaula();
    }
    
    private void setModelTaula() throws ParseException{
        modelTaulaPartides = new ModelTaulaDadesJoc();
        modelTaulaPartides.setPartides(obtenirPartides());
        this.taula.setModel(modelTaulaPartides);
        this.model_taula();//TODO Revisar! no aplica els canvis
    }
    
    public void model_taula(){
        taula.getColumnModel().getColumn(0).setWidth(10);
        taula.getColumnModel().getColumn(1).setWidth(30);
        taula.getColumnModel().getColumn(2).setWidth(30);
        
        taula.getTableHeader().setBackground(new Color(251,139,36));
        
        taula.setForeground(new Color(23,33,33));
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        taula.getColumnModel().getColumn(0).setCellRenderer(tcr);
        taula.getColumnModel().getColumn(1).setCellRenderer(tcr);
        taula.getColumnModel().getColumn(2).setCellRenderer(tcr);

    }
    
    public ArrayList<Partida> obtenirPartides() throws ParseException{
            
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        
        ArrayList<Partida> llista = new ArrayList();
        llista.add(new Partida(1, df.parse("21/10/19"), df.parse("27/10/19")));
        llista.add(new Partida(2, df.parse("28/10/19"), df.parse("05/11/19")));
        llista.add(new Partida(3, df.parse("06/11/19"), df.parse("13/11/19")));

        return llista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taula = new javax.swing.JTable();
        btInfo = new javax.swing.JButton();
        btModifica = new javax.swing.JButton();
        btElimina = new javax.swing.JButton();
        cbJoc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 215, 41));

        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(taula);

        btInfo.setText("Obtenir dades");
        btInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoActionPerformed(evt);
            }
        });

        btModifica.setText("Modifica");
        btModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificaActionPerformed(evt);
            }
        });

        btElimina.setText("Elimina");
        btElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbJoc, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btElimina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(cbJoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btInfo)
                        .addGap(18, 18, 18)
                        .addComponent(btModifica)
                        .addGap(18, 18, 18)
                        .addComponent(btElimina)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoActionPerformed
        int fila = this.taula.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Cal seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Partida partida = modelTaulaPartides.getPartides().get(fila);
        String mensaje = "Dades de la partida seleccionada\n"
                + "Número de partida: " + partida.getNum_jornada() + "\n"
                + "Data inici: " + partida.getData_inici() + "\n"
                + "Data final: " + partida.getData_final() + "\n"
                + "Professor responsable: " + partida.getJoc().getProfessor();
        JOptionPane.showMessageDialog(this, mensaje, "Dades", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btInfoActionPerformed

    private void btModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificaActionPerformed
        int fila = this.taula.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Cal seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //TODO modififa segons les noves dades que s'han canviat a la mateixa taula
        
        
    }//GEN-LAST:event_btModificaActionPerformed

    private void btEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminaActionPerformed
        int fila = this.taula.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Cal seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Partida partida = modelTaulaPartides.getPartides().get(fila);
        //TODO delete partida
        
    }//GEN-LAST:event_btEliminaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM05BGestionaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM05BGestionaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM05BGestionaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM05BGestionaJoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PM05BGestionaJoc().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(PM05BGestionaJoc.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btElimina;
    private javax.swing.JButton btInfo;
    private javax.swing.JButton btModifica;
    private javax.swing.JComboBox<String> cbJoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable taula;
    // End of variables declaration//GEN-END:variables
}
