/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistes.panels;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import vistes.PM01Login;
import vistes.PM05ACrearJoc;
import vistes.PM05BGestionaJoc;

/**
 *
 * @author montse
 */
public class PM05Joc extends javax.swing.JPanel {

    /**
     * Creates new form PM04Modifica
     */
    public PM05Joc() {
        initComponents();
        
        this.setSize(750, 625);
        this.setLayout(null);
        
        jPJoc.setSize(750, 625);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPJoc = new javax.swing.JPanel();
        btCrear = new javax.swing.JButton();
        btModifica = new javax.swing.JButton();

        setBackground(new java.awt.Color(162, 215, 41));

        jPJoc.setBackground(new java.awt.Color(162, 215, 41));

        btCrear.setText("Crear joc de preguntes");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        btModifica.setText("Llistar joc de preguntes");
        btModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPJocLayout = new javax.swing.GroupLayout(jPJoc);
        jPJoc.setLayout(jPJocLayout);
        jPJocLayout.setHorizontalGroup(
            jPJocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPJocLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPJocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btModifica, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(btCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPJocLayout.setVerticalGroup(
            jPJocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPJocLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPJoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPJoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        PM05ACrearJoc f5 = new PM05ACrearJoc();
        f5.setVisible(true);
        f5.pack();
        f5.setLocationRelativeTo(null);
        f5.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_btCrearActionPerformed

    private void btModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificaActionPerformed
        try {
            PM05BGestionaJoc f5b = new PM05BGestionaJoc();
            f5b.setVisible(true);
            f5b.pack();
            f5b.setLocationRelativeTo(null);
            f5b.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        } catch (ParseException ex) {
            Logger.getLogger(PM05Joc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btModificaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrear;
    private javax.swing.JButton btModifica;
    private javax.swing.JPanel jPJoc;
    // End of variables declaration//GEN-END:variables
}
